---
title: "Validators"
output:
  knitrBootstrap::bootstrap_document:
    menu: FALSE
    theme: Flatly
  df_print: kable
---

```{r setup, include=FALSE}
library(knitr)
library(knitrBootstrap)
```


``` {r message=FALSE, echo=FALSE}
source("routine.R")
```

# Overview

This report is generated by Opal [opal-analysis-validate](https://github.com/obiba/opal-analysis-validate) plugin to demonstrate how custom analysis routines can be integrated into an Opal project. This plugin uses the R [validate ](https://www.rdocumentation.org/packages/validate) package.

# Results

## Summary Barplot {data-icon="fa-signal"}

``` {r echo=FALSE, bootstrap.thumbnail.size="col-xs-12", fig.width=12}
barplot(summaryData[["confront"]], main="")
```

## Summary Table

``` {r echo=FALSE}
kable(summaryData[["summary"]])
```

## Validator Rules

``` {r echo=FALSE}
kable(rules)
```

## Errors

``` {r echo=FALSE, results="asis"}
if (length(errorList) > 0) {
  gsub("\\|x", "|", kable(unlist(errorList)))
} else {
  gsub("\\|x", "|", kable(c("No errors found.")))
}
```
